queue_rules:
  - name: dependabot-updates
    queue_conditions:
      - author=dependabot[bot]
      - base=development
    merge_conditions:
      - check-success=lints
      - check-success=check
    merge_method: squash

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
