queue_rules:
  - name: dependabot-updates
    conditions:
      - check-success=lints
      - check-success=check

pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - base=development
    actions:
      queue:
        method: merge
        name: dependabot-updates
