[package]
name = "mc-server-pinger"
version = "0.1.0-alpha.2"
authors = ["Petr Portnov <me@progrm-jarvis.ru>"]
edition = "2018"
# Basic properties
description = "Command line utility for pinging Minecraft servers via Server List Ping protocol"
license = "Apache-2.0"
repository = "https://github.com/JarvisCraft/mc-server-pinger"
# crates.io search metadata
keywords = ["minecraft", "ping"]
categories = ["command-line-utilities", "network-programming"]

[dependencies]
craftping = { version = "0.2.1", features = ["async-tokio"] }
tokio = { version = "1.2.0", features = ["rt", "time", "macros"] }
clap = "3.0.0-beta.2"
peg = "0.6.3"
