name: Lints

on: [ pull_request, merge_group ]

jobs:
  check:
    name: Cargo Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          toolchain: 1.76.0
      - uses: olix0r/cargo-action-fmt/setup@v2.0.1
      - run: cargo check -q --message-format=json | cargo-action-fmt

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          # we have to use nightly since come important options are not stable yet
          toolchain: nightly
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1.1.0

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          toolchain: 1.76.0
          components: clippy
      - uses: auguwu/clippy-action@1.3.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}

  doc:
    name: Doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          toolchain: 1.76.0
      - uses: olix0r/cargo-action-fmt/setup@v2.0.1
      - run: cargo doc --no-deps --message-format=json | cargo-action-fmt
