name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    strategy:
      matrix:
        target:
          # Linux
          # - aarch64-unknown-linux-gnu
          # - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          # Windows
          # - i686-pc-windows-msvc
          - x86_64-pc-windows-msvc
          # MacOS
          - x86_64-apple-darwin
        include:
          # Linux
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            binary-name: mc-server-pinger
            artifact-name: mc-server-pinger-linux-aarch64
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
            binary-name: mc-server-pinger
            artifact-name: mc-server-pinger-linux-i686
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            binary-name: mc-server-pinger
            artifact-name: mc-server-pinger-linux-x86_64
          # Windows
          - target: i686-pc-windows-msvc
            os: windows-latest
            binary-name: mc-server-pinger.exe
            artifact-name: mc-server-pinger-windows-i686.exe
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            binary-name: mc-server-pinger.exe
            artifact-name: mc-server-pinger-windows-x86_64.exe
          # MacOS
          - target: x86_64-apple-darwin
            os: macOS-latest
            binary-name: mc-server-pinger
            artifact-name: mc-server-pinger-windows-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Move binary
        run: mv target/${{ matrix.target }}/release/${{ matrix.binary-name }} ${{ matrix.artifact_name }}

      - name: Strip binary
        run: strip ${{ matrix.binary-name }}

      - name: Generate checksum
        run: shasum -a 256 ${{ matrix.binary-name }} > ${{ matrix.artifact_name }}.sha256

      - name: Upload release binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mc-server-pinger-*
          file_glob: true
          tag: ${{ github.ref }}

