name: Test

on: [ push, merge_group ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          toolchain: 1.76.0
      - run: cargo test --all-features
